language: scala

jdk:
- openjdk11

jobs:
  include:
  - stage: Tests
    name: Unit tests
    script:
    - sbt compile test

  - stage: Publish snapshot
    name: Publish snapshot
    on:
      branch: master
    before_script:
    - gpg --import signingkey.asc
    script:
    - sbt publish

  - stage: Publish release
    name: Publish release
    on:
      tags: true
    before_script:
      - gpg --import signingkey.asc
    script:
      - sbt publish

before_install:
- openssl aes-256-cbc -K $encrypted_171b1c559d7b_key -iv $encrypted_171b1c559d7b_iv
  -in signingkey.asc.enc -out signingkey.asc -d
